### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by WalterOkumu** [WalterOkumu/tv-show#41]
## Project Set-Up

We successfully set up our project as follows:

- Set up Gitflow
- Set up webpack
- Set up a JavaScript testing library (Jest)

## Group Members

- @WalterOkumu 
- @AlierPM 

## Link to Group Kanban

- [https://github.com/users/WalterOkumu/projects/2/views/1](https://github.com/users/WalterOkumu/projects/2/views/1)

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Suggested changes
- [ ] [REQUIRED] Please paste the link to your [GitHub Kanban Project](https://github.com/users/WalterOkumu/projects/2/views/1) in your issue description!

![image](https://user-images.githubusercontent.com/63915024/188513706-93cc55ba-4918-448b-b487-bca630f9cb3c.png)

- [ ] [REQUIRED] In fact, there should be `15 cards` for a `2-person team`, and `20 cards` for a `3-person team`. But you have a total of `40 cards`. Please remove the duplicate cards from the Kanban project and close the issues!

![image](https://user-images.githubusercontent.com/63915024/188513644-04b865b3-4510-47ec-b89a-aaff6f56db49.png)


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by BertrandConxy** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 

- Kanban is set up very well

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
